TianFuWeb/urls.py
# _*_ encoding:utf-8 _*_
"""TianFuWeb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve
from users.views import LoginView,LogoutView,RegisterView,ActiveUserView, ForgetPwdView,ResetView,ModifyPwdView,IndexView
from organization.views import OrgView
from TianFuWeb.settings import MEDIA_ROOT,STATIC_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',IndexView.as_view(),name="index"),
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="user_active"),
    url(r'^forgetpwd/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)/$',serve,{"document_root":MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)/$', serve, {"document_root": STATIC_ROOT}),

    #课程url配置
    url(r'^org/',include('organization.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^users/', include('users.urls')),

    url(r'^ueditor/',include('DjangoUeditor.urls'))
]

#全局404页面配置
handler404='users.views.page_not_found'
handler500='users.views.page_error'

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/courses/models.py
# _*_ encoding:utf-8 _*_

from datetime import datetime
from django.db import models
from organization.models import CourseOrg
from DjangoUeditor.models import UEditorField

# Create your models here.


class Course(models.Model):
    course_org=models.ForeignKey(CourseOrg,verbose_name=u'课程机构',null=True,blank=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=50,verbose_name=u'课程名')
    desc=models.CharField(max_length=300,verbose_name=u'课程描述')
    detail=UEditorField(verbose_name=u"课程详情", imagePath="course/ueditor/", width=1000, height=300,
                        filePath="course/ueditor/", default='')
    is_banner=models.BooleanField(default=False,verbose_name=u'是否轮播')
    teacher=models.CharField(max_length=50,default=u'',verbose_name=u'讲师',null=True,blank=True)
    degree=models.CharField(choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')),max_length=2)
    learn_times=models.IntegerField(default=0,verbose_name=u'学习时长(分钟数)')
    students=models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums=models.IntegerField(default=0,verbose_name=u'收藏人数')
    image=models.ImageField(upload_to='courses/%Y/%m',verbose_name=u'封面图',max_length=100)
    click_nums=models.IntegerField(default=0,verbose_name=u'点击数')
    category=models.CharField(default=u'媒体',max_length=20,verbose_name=u'课程类别')
    tag=models.CharField(default='',verbose_name=u'课程标签',max_length=10)
    add_time=models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    youneed_know=models.CharField(default='',max_length=300,verbose_name=u'课程须知')
    teacher_tell=models.CharField(default='',max_length=300,verbose_name=u'老师告诉')

    class Meta:
        verbose_name=u'课程'
        verbose_name_plural=verbose_name

    def get_zj_nums(self):
        # 获取课程章节数
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course=models.ForeignKey(Course,verbose_name=u'课程',on_delete=models.CASCADE)
    name=models.CharField(max_length=100,verbose_name=u'章节名')
    add_time=models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name=u'章节'
        verbose_name_plural=verbose_name

    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟数)')
    url = models.CharField(default='', max_length=200, verbose_name=u'访问地址')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

        def __str__(self):
            return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'名称')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/organization/views.py
# _*_ encoding:utf-8 _*_
from django.shortcuts import render
from django.contrib.auth import authenticate,login
from django.views.generic import View
from pure_pagination import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponse
from .models import CourseOrg,CityDict,team,pictures,works,task
from .forms import UserOfferForm
from courses.models import CourseOrg,Course
from operation.models import UserFavorite
from django.db.models import Q

# Create your views here.
class OrgView(View):
    def get(self,request):
        all_orgs=CourseOrg.objects.all()
        hot_orgs=all_orgs.order_by("-click_nums")[:3]
        all_citys=CityDict.objects.all()

        search_keywords = request.GET.get('keywords', "")
        if search_keywords:
            all_orgs = all_orgs.filter(
                Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords))

        #取出筛选城市
        city_id=request.GET.get("city","")
        if city_id:
            all_orgs=all_orgs.filter(city_id=int(city_id))
        #类别筛选
        category=request.GET.get('ct',"")
        if category:
            all_orgs=all_orgs.filter(category=category)
        sort=request.GET.get('sort',"")
        if sort:
            if sort=="students":
                all_orgs=all_orgs.order_by("-students")
            elif sort=="courses":
                all_orgs=all_orgs.order_by("-course_nums")

        #对课程机构进行分页
        org_nums=all_orgs.count()
        try:
            page=request.GET.get('page',1)
        except PageNotAnInteger:
            page=1
        p=Paginator(all_orgs,1,request=request)
        orgs=p.page(page)
        return render(request,"org-list.html",{
            'all_orgs':orgs,
            'all_citys':all_citys,
            'org_nums':org_nums,
            'city_id':city_id,
            'category':category,
            'hot_orgs':hot_orgs,
            'sort':sort,
        })

class AddOfferView(View):
    #用户添加提供信息
    def post(self,request):
        useroffer_form=UserOfferForm(request.POST)
        if useroffer_form.is_valid():
            user_offer=useroffer_form.save(commit=True)
            return HttpResponse('{"status":"success"}',content_type='application/json')
        else:
            return HttpResponse('{"status":"fail","msg":"添加出错"}',content_type='application/json')

class OrgHomeView(View):
    def get(self,request,org_id):
        current_page = "home"
        course_org=CourseOrg.objects.get(id=int(org_id))
        course_org.click_nums+=1
        course_org.save()
        #判断是否收藏
        has_fav=False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user,fav_id=course_org.id,fav_type=2):
                has_fav=True
        all_courses=course_org.course_set.all()[:3]
        return render(request,'org-detail-homepage.html',{
            'all_courses':all_courses,
            'course_org':course_org,
            'current_page': current_page,
            'has_fav':has_fav,
        })

class OrgCourseView(View):
    def get(self,request,org_id):
        current_page="course"
        course_org=CourseOrg.objects.get(id=int(org_id))
        # 判断是否收藏
        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type=2):
                has_fav = True
        all_courses=course_org.course_set.all()

        # 对课程机构进行分页
        course_nums = all_courses.count()
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_courses, 1, request=request)
        courses = p.page(page)
        return render(request,'org-detail-course.html',{
            'all_courses':courses,
            'course_org':course_org,
            'course_nums':course_nums,
            'current_page':current_page,
            'has_fav': has_fav,
        })

class OrgDescView(View):
    def get(self,request,org_id):
        current_page = "desc"
        course_org=CourseOrg.objects.get(id=int(org_id))
        # 判断是否收藏
        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type=2):
                has_fav = True
        return render(request,"org-detail-desc.html",{
            'current_page':current_page,
            'course_org':course_org,
            'has_fav': has_fav,
        })

class AddFavView(View):
    #用户收藏以及取消收藏
    def post(self,request):
        fav_id=request.POST.get('fav_id',0)
        fav_type=request.POST.get('fav_type',0)
        if not request.user.is_authenticated:
            return HttpResponse('{"status":"fail","msg":"用户未登录"}',content_type='application/json')
        exist_records=UserFavorite.objects.filter(user=request.user,fav_id=int(fav_id),fav_type=int(fav_type))
        if exist_records:
            #记录已经存在，表示用户想取消收藏
            exist_records.delete()
            if int(fav_type==1):
                course=Course.objects.get(id=int(fav_id))
                course.fav_nums-=1
                if course.fav_nums<0:
                    course.fav_nums=0
                course.save()
            elif int(fav_type==2):
                course_org=CourseOrg.objects.get(id=int(fav_id))
                course_org.fav_nums-=1
                if course_org.fav_nums<0:
                    course_org.fav_nums=0
                course_org.save()
            elif int(fav_type==3):
                teamm=team.objects.get(id=int(fav_id))
                teamm.fav_nums-=1
                if teamm.fav_nums<0:
                    teamm.fav_nums=0
                teamm.save()
            return HttpResponse('{"status":"success","msg":"收藏"}',content_type='application/json')
        else:
            user_fav=UserFavorite()
            if int(fav_id)>0 and int(fav_type)>0:
                user_fav.user=request.user
                user_fav.fav_id=int(fav_id)
                user_fav.fav_type=int(fav_type)
                user_fav.save()
                if int(fav_type == 1):
                    course = Course.objects.get(id=int(fav_id))
                    course.fav_nums += 1
                    course.save()
                elif int(fav_type == 2):
                    course_org = CourseOrg.objects.get(id=int(fav_id))
                    course_org.fav_nums += 1
                    course_org.save()
                elif int(fav_type == 3):
                    teamm = team.objects.get(id=int(fav_id))
                    teamm.fav_nums += 1
                    teamm.save()
                return HttpResponse('{"status":"fail","msg":"已收藏"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"fail","msg":"收藏出错"}', content_type='application/json')

#天釜在线列表页
class TeamListView(View):
    def get(self,request):
        all_teams=team.objects.all()
        team_nums = all_teams.count()

        search_keywords = request.GET.get('keywords', "")
        if search_keywords:
            all_teams = all_teams.filter(
                Q(name__icontains=search_keywords) | Q(points__icontains=search_keywords))

        sort = request.GET.get('sort', "")
        if sort:
            if sort == "hot":
                all_teams = all_teams.order_by("-click_nums")
        return render(request,"teachers-list.html",{
            'all_teams':all_teams,
            'team_nums':team_nums,
            'sort':sort,
        })

class TeamDetailView(View):
    def get(self,request,team_id):
        teams=team.objects.get(id=int(team_id))
        teams.click_nums+=1
        teams.save()
        all_pictures=pictures.objects.filter(forteam=teams)
        has_team_faved=False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user,fav_type=3,fav_id=teams.id):
                has_team_faved=True
        return render(request,"teacher-detail.html",{
            'teams':teams,
            'all_pictures':all_pictures,
            'has_team_faved':has_team_faved,
        })

class WorkListView(View):
    def get(self,request):
        all_works=works.objects.all()
        work_nums=all_works.count()

        search_keywords = request.GET.get('keywords', "")
        if search_keywords:
            all_works = all_works.filter(
                Q(title__icontains=search_keywords)| Q(author__icontains=search_keywords) | Q(points__icontains=search_keywords))

        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_works, 3, request=request)
        workss = p.page(page)
        return render(request,"works-list.html",{
            'all_works':workss,
            'work_nums':work_nums,
        })

class TaskView(View):
    def get(self,request):
        all_tasks=task.objects.all()
        count=all_tasks.count()
        return render(request,"task.html",{
            'all_tasks':all_tasks,
            'count':count,
        })

templates/base.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}课程分类列表 - 天釜共享在线网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
    {% block custom_css %}{% endblock %}
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>17794229835</b></p></div>
					<!--登录后跳转-->



                        {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="/users/info/">进入个人中心</a>
	                                <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="/users/message/">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                        {% else %}
                         <a style="color:white" class="fr registerbtn" href="/register/">注册</a>
                        <a style="color:white" class="fr loginbtn" href="/login/">登录</a>
                        {% endif %}


				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="/"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程分类</li>
                                <li data-value="team">天釜在线</li>
                                <li data-value="works">天釜有品</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if request.path == '/' %}class="active"{% endif %} ><a href="/">首页</a></li>
							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
								<a href="/course/list/">
									公开课<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>
							<li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}><a href="/org/list/">课程分类</a></li>
							<li {% if request.path|slice:'9' == '/org/team' %}class="active"{% endif %}>
								<a href="/org/team/list/">天釜在线</a>
							</li>
                            <li {% if request.path|slice:'15' == '/org/works/list' %}class="active"{% endif %}>
								<a href="/org/works/list/">天釜有品</a>
							</li>
                            <li {% if request.path|slice:'9' == '/org/task' %}class="active"{% endif %}>
								<a href="/org/task/">任务发布</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>课程分类</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}

{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="/static/images/footlogo.png"/></a></li>
					<li class="code"><img src="/static/images/code.jpg"/><p class="center">扫描QQ进群</p></li>
					<li class="third"><img class="fl" src="/static/images/tell.png"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2018 39.105.50.204 天釜共享-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2018 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="totop"></li>
    </ul>
</section>
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}课程列表页 - 天釜共享在线网{% endblock %}

{% block custom_bread %}
{% endblock %}

{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="#">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">天釜提供</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">多方授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">多方授课<br/>天釜提供</p>
						<a class="more" href="/course/list/">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for course in courses %}
                                    <li>
                                        <a href="/course/detail/{{ course.id }}/">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ course.image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                    {% for banner_course in banner_courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="/course/detail/{{ banner_course.id }}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ banner_course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="/course/detail/{{ banner_course.id }}">
                                        <h2 title="django入门">{{ banner_course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ banner_course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ banner_course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ banner_course.course_org.name}}</span>
                                    <span class="star fr">{{ banner_course.fav_nums }}</span>
                                </div>
                            </div>
                    {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程分类</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">天釜名作<br/>权威认证</p>
						<a class="more" href="/org/list/">查看更多 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for course_org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:'5' %}five{% endif%}">
                                    <a href="/org/home/{{ course_org.id }}/">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ course_org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ course_org.name }}">{{ course_org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="/modify_pwd/" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/usercenter-fav-course.html
{% extends "usercenter-base.html" %}
{% block title %}我的收藏 - 天釜共享在线网{% endblock %}

<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="/users/info/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li ><a href="/users/myfav/org/">课程分类</a> </li>
                        <li><a href="/users/myfav/team/">工作室</a></li>
                        <li class="active"><a href="/users/myfav/course/">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="/course/detail/{{ course.id }}/">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="/course/detail/{{ course.id }}/"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}